user_input = input("문장 입력 : ")
print("#" * 20)
print(f'대문자 변환 : {user_input.upper()}')
print(f'소문자 변환 : {user_input.lower()}')
print(f'문자열 길이 : {len(user_input)}')
print(f'공백으로 분리 : {user_input.split()}')
print(f'문자로 분리 : {user_input.split(".")}')
print(f'o의 위치 : {user_input.find("o")}')
print(f'o의 개수 : {user_input.count("o")}')
print(f'Python을 AI로 교체 : {user_input.replace("Python", "AI")}')