# 입출력을 이용한 연산 프로그램
print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^")
print("        연산 프로그램          ")
print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^")
a = int(input("첫번째 값 : "))
b = int(input("두번째 값 : "))
print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^")

print(f'{a} + {b} = {a+b}')
print(f'{a} - {b} = {a-b}')
print(f'{a} * {b} = {a*b}')
print(f'{a} ** {b} = {a**b}')
print(f'{a} / {b} = {a/b}')
print(f'{a} // {b} = {a//b}')
print(f'{a} % {b} = {a%b}')
